name: Generate Package.resolved for All Packages

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-package-resolved:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Swift
      run: |
        echo "Setting up Swift..."
        # Swift is pre-installed on macOS, but we ensure it’s available
        swift --version

    - name: Find and resolve all Package.swift files
      run: |
        echo "Finding and resolving all Package.swift files..."

        # Find all Package.swift files and loop through them
        find . -name "Package.swift" -print0 | while IFS= read -r -d '' package; do
          package_dir=$(dirname "$package")
          echo "Resolving dependencies in $package_dir"
          
          # Change to the directory containing Package.swift
          cd "$package_dir"
          
          # Resolve dependencies
          swift package resolve
          
          # Check if Package.resolved was created
          if [ ! -f ./Package.resolved ]; then
            echo "Package.resolved not found in $package_dir!"
            exit 1
          fi

          # Return to the root of the repository
          cd - > /dev/null
        done

    - name: Commit and push all Package.resolved files
      run: |
        echo "Committing and pushing all Package.resolved files..."
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add '**/Package.resolved'
        git commit -m "Add or update Package.resolved files generated by GitHub Actions" || echo "No changes to commit"
        git push
